import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased dark`}
        >
          <header>
        <nav className="flex justify-around p-3">
          <h1>Sponsor</h1>
          <div className="gap-2 flex">
          <Button variant="outline">About Us</Button>
          <Button variant="outline">Login</Button>
          <Button variant="outline">Sign Up</Button>
          </div>
        </nav>
            </header>
        {children}
      <footer className="text-center">Contact Us</footer>
      </body>
    </html>
  );
}
